### ISSUE TITLE
Add Contributors to README

### ISSUE THREAD

**Issue by eevajonnapanula** [turkupy/turkupy.github.io#28]
What we would like to have, is a section in Readme, which lists all the users, who have contributed to this repository.

For example [this Github Action](https://github.com/marketplace/actions/contribute-list) could be used to accomplish this. It should maybe run every time there is a push to dev. (So actually, when a PR gets merged as direct pushes to dev are prevented)

**Comment by vivek32ta** [comment]
Hi @eevajonnapanula 

I'd love to take this up!

**Comment by eevajonnapanula** [comment]
Hey @vivek32ta , the issue is yours! 😊  If there is anything unclear or anything at all, please do ask. 

Also a note - we are still in progress of updating the contribution guidelines and code of conduct, but [you can see them here](https://github.com/turkupy/turkupy.github.io/blob/feature/add-contributing-guidelines/CONTRIBUTING.md)

**Comment by vivek32ta** [comment]
Hey @eevajonnapanula 

In `.\.github\workflows\deploy.yml` I have appended
```
- name: Add Contributor
  uses: akhilmhdh/contributors-readme-action@v2.0.1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But to test it we need to push the change to dev. Would that be a good idea?
